### ISSUE TITLE
Feedback on week 13 project progress for CS2113T-F11-3

### ISSUE THREAD

**Issue by nus-pe-script** [AY1920S1-CS2113T-F11-3/main#230]
## Team progress for `v1.4`
* Milestone `v1.4` properly managed:
   * [x] A suitable deadline set [your deadline: 2019-11-11] (:heavy_check_mark: well done!)
   * [x] All issues in this milestone are closed(:heavy_check_mark: well done!)
   * [x] Milestone explicitly closed(:heavy_check_mark: well done!)
* [x] New JAR released on GitHub in the past 2 weeks (:heavy_check_mark: well done!)
## Individual progress of @limryan for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-F11-3/main/pull/214 https://github.com/AY1920S1-CS2113T-F11-3/main/pull/213 https://github.com/AY1920S1-CS2113T-F11-3/main/pull/211 https://github.com/AY1920S1-CS2113T-F11-3/main/pull/199 https://github.com/AY1920S1-CS2113T-F11-3/main/pull/190 https://github.com/AY1920S1-CS2113T-F11-3/main/pull/214 https://github.com/AY1920S1-CS2113T-F11-3/main/pull/213 https://github.com/AY1920S1-CS2113T-F11-3/main/pull/211 https://github.com/AY1920S1-CS2113T-F11-3/main/pull/199 https://github.com/AY1920S1-CS2113T-F11-3/main/pull/190 https://github.com/AY1920S1-CS2113T-F11-3/main/issues/177 https://github.com/AY1920S1-CS2113T-F11-3/main/issues/174 https://github.com/AY1920S1-CS2113T-F11-3/main/issues/168 https://github.com/AY1920S1-CS2113T-F11-3/main/issues/148 https://github.com/AY1920S1-CS2113T-F11-3/main/issues/147 https://github.com/AY1920S1-CS2113T-F11-3/main/issues/144 https://github.com/AY1920S1-CS2113T-F11-3/main/issues/135 https://github.com/AY1920S1-CS2113T-F11-3/main/issues/88 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @lee761 for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-F11-3/main/pull/192 https://github.com/AY1920S1-CS2113T-F11-3/main/issues/197 https://github.com/AY1920S1-CS2113T-F11-3/main/issues/172 https://github.com/AY1920S1-CS2113T-F11-3/main/issues/139 https://github.com/AY1920S1-CS2113T-F11-3/main/issues/133 https://github.com/AY1920S1-CS2113T-F11-3/main/issues/132 https://github.com/AY1920S1-CS2113T-F11-3/main/issues/88 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @jokeryan for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-F11-3/main/pull/227 https://github.com/AY1920S1-CS2113T-F11-3/main/pull/223 https://github.com/AY1920S1-CS2113T-F11-3/main/pull/219 https://github.com/AY1920S1-CS2113T-F11-3/main/pull/196 https://github.com/AY1920S1-CS2113T-F11-3/main/pull/191 https://github.com/AY1920S1-CS2113T-F11-3/main/issues/179 https://github.com/AY1920S1-CS2113T-F11-3/main/issues/178 https://github.com/AY1920S1-CS2113T-F11-3/main/issues/175 https://github.com/AY1920S1-CS2113T-F11-3/main/issues/173 https://github.com/AY1920S1-CS2113T-F11-3/main/issues/170 https://github.com/AY1920S1-CS2113T-F11-3/main/issues/169 https://github.com/AY1920S1-CS2113T-F11-3/main/issues/166 https://github.com/AY1920S1-CS2113T-F11-3/main/issues/164 https://github.com/AY1920S1-CS2113T-F11-3/main/issues/163 https://github.com/AY1920S1-CS2113T-F11-3/main/issues/160 https://github.com/AY1920S1-CS2113T-F11-3/main/issues/159 https://github.com/AY1920S1-CS2113T-F11-3/main/issues/158 https://github.com/AY1920S1-CS2113T-F11-3/main/issues/156 https://github.com/AY1920S1-CS2113T-F11-3/main/issues/155 https://github.com/AY1920S1-CS2113T-F11-3/main/issues/154 https://github.com/AY1920S1-CS2113T-F11-3/main/issues/153 https://github.com/AY1920S1-CS2113T-F11-3/main/issues/152 https://github.com/AY1920S1-CS2113T-F11-3/main/issues/151 https://github.com/AY1920S1-CS2113T-F11-3/main/issues/150 https://github.com/AY1920S1-CS2113T-F11-3/main/issues/148 https://github.com/AY1920S1-CS2113T-F11-3/main/issues/146 https://github.com/AY1920S1-CS2113T-F11-3/main/issues/143 https://github.com/AY1920S1-CS2113T-F11-3/main/issues/142 https://github.com/AY1920S1-CS2113T-F11-3/main/issues/141 https://github.com/AY1920S1-CS2113T-F11-3/main/issues/137 https://github.com/AY1920S1-CS2113T-F11-3/main/issues/136 https://github.com/AY1920S1-CS2113T-F11-3/main/issues/134 https://github.com/AY1920S1-CS2113T-F11-3/main/issues/88 https://github.com/AY1920S1-CS2113T-F11-3/main/issues/13 https://github.com/AY1920S1-CS2113T-F11-3/main/issues/12 https://github.com/AY1920S1-CS2113T-F11-3/main/issues/4 (:heavy_check_mark: well done!)
* [x] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @ziyun99 for `v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-F11-3/main/pull/194 https://github.com/AY1920S1-CS2113T-F11-3/main/pull/186 https://github.com/AY1920S1-CS2113T-F11-3/main/pull/194 https://github.com/AY1920S1-CS2113T-F11-3/main/pull/186 https://github.com/AY1920S1-CS2113T-F11-3/main/issues/165 https://github.com/AY1920S1-CS2113T-F11-3/main/issues/164 https://github.com/AY1920S1-CS2113T-F11-3/main/issues/88 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)

Tutor: @leowweixiang

Please reply in this thread if there are any inaccuracies in the above observations.

 <sub> Note: the above observation was done by the CS2113-feedback-bot and covers changes up to 2019-11-15 00:00:00 only. If you think the above observation is incorrect, please let us know by replying in this thread. Please include links to relevant PRs/comments in your response.</sub>
